server.port: 17002
server.error.include-message: always

logging:
  level:
    root: INFO
    se.magnus: DEBUG

spring.data.mongodb:
  host: localhost
  port: 27017
  database: recommendation-db

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"