server.port: 17001
server.error.include-message: always
logging:
  level:
    root: INFO
    se.magnus.microservices: DEBUG

spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db